module.exports = {
    webAppName:"Queen Site",
    courses:{
        it:[
            {
                lectureName:"Things You have to Know About The IT Industry",
                iframeLink:'https://www.youtube.com/embed/eimzeNf_Ty8',
                link:"https://youtu.be/eimzeNf_Ty8",
                instructor:"ALUX",
                description:"How big is the IT Industry? What does the IT Industry mean? What are the best jobs in the IT Industry? How can you get started in the IT Industry?, How to code?",
                completed:false,
            },
            {
                lectureName:"Trending Tech Courses in IT Sector",
                iframeLink:'https://www.youtube.com/embed/fwIxyDx8Dck',
                link:"https://youtu.be/fwIxyDx8Dck",
                instructor:"Quick Support",
                description:" IT फील्ड में इंडियाकाफी तेजी से आगे बढ़ रहा है। ऐसे में IT सेक्टर में बहुत सारी पॉसिबिलिटीज अवेलेबल हैं यानी इस फील्ड में कई तरह के शॉर्ट टर्म और लॉन्ग टर्म कोर्सेज किये जा सकते हैं।",
                completed:false,
            },
            {
                lectureName:"Web development full course",
                iframeLink:'https://www.youtube.com/embed/Q33KBiDriJY',
                link:"https://youtu.be/20v8zSo2v18",
                instructor:"Edureka",
                description:"This Edureka Web Development Full Course video will help you understand and learn Web Development in detail. This Web Development Tutorial is ideal for both beginners as well as professionals who want to master Web Development technologies.",
                completed:false,
            },
            {
                lectureName:"Android development full course",
                iframeLink:'https://www.youtube.com/embed/mXjZQX3UzOs',
                link:"https://youtu.be/mXjZQX3UzOs",
                instructor:"Code With Harry",
                description:"In this Android App Development tutorial, we will learn how to make beautiful android applications from scratch in Hindi. This Android tutorial in Hindi will teach you how to make Android apps that sell from scratch. We will learn to make apps and publish them to the play store in 2022.",
                completed:false,
            },
            {
                lectureName:"Blockchain development full course",
                iframeLink:'https://www.youtube.com/embed/gyMwXuJrbJQ',
                link:"https://youtu.be/gyMwXuJrbJQ",
                instructor:"FreeCodeCamp.org",
                description:"This course will give you a full introduction into all of the core concepts related to blockchain, Solidity, full-stack Web3 dapps, decentralized finance (DeFi), JavaScript, TypeScript, Chainlink, Ethereum, DAOs, moralis, aave, IPFS, and more.",
                completed:false,
            },
        ],

        bussiness:[
            {
                lectureName:"How to Grow Your Small Business Successfully",
                iframeLink:'https://www.youtube.com/embed/wMUStCZhinM',
                link:"https://youtu.be/wMUStCZhinM",
                instructor:"Rewires",
                description:"In this video, we will share with you some of the main and essential advice and rule which famous and successful entrepreneurs like jeff Bezos steve jobs and bill gates tried to share at various places.",
                completed:false,
            },
            {
                lectureName:"How to start a Business|Being an Entrepreneur in India",
                iframeLink:'https://www.youtube.com/embed/uOA5h_KdjO4',
                link:"https://youtu.be/uOA5h_KdjO4",
                instructor:"Dhruv Rathee",
                description:"This video is all you need to know on how to start a business or a start up in India. I explain the types of business entities that exist in India, their governmental regulations and their tax regulations.",
                completed:false,
            },
            {
                lectureName:"कैसे खिंचा चला आता है Customer!",
                iframeLink:'https://www.youtube.com/embed/h5-LpwwQJ6M',
                link:"https://youtu.be/h5-LpwwQJ6M",
                instructor:"Dr. Vivek Bindra",
                description:"Marketing & Sales are two pillars of a successful business. However, people often confuse the two terms. Where Sales increase the revenue of the business, Marketing helps in creating the recall value amidst the target niche. ",
                completed:false,
            },
            {
                lectureName:"How to Start a Business with No Money?",
                iframeLink:'https://www.youtube.com/embed/Rf4rU1hwQXc',
                link:"https://youtu.be/Rf4rU1hwQXc",
                instructor:"Sandeep Maheshwari",
                description:"Sandeep Maheshwari is a name among millions who struggled, failed and surged ahead in search of success, happiness and contentment. Just like any middle class guy, he too had a bunch of unclear dreams and a blurred vision of his goals in life.",
                completed:false,
            },
            {
                lectureName:"How to programming",
                iframeLink:'<iframe width="560" height="315" src="https://www.youtube.com/embed/JYnEbcTCyVI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                link:"https://youtu.be/UmnCZ7-9yDY",
                instructor:"Aman Dhattarval",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
        ],


        personalDevelopment:[
            {
                lectureName:"How to programming",
                iframeLink:'https://www.youtube.com/embed/JYnEbcTCyVI',
                link:"https://youtu.be/eKqY-oP1d_Y",
                instructor:"Shraddha Khapra",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
            {
                lectureName:"Python in 1 video",
                iframeLink:'https://www.youtube.com/embed/JYnEbcTCyVI',
                link:"https://youtu.be/vLqTf2b6GZw",
                instructor:"Aman Dhattarval and Shraddha Khapra",
                description:"This video shows installation of 2 Python editors, both are free to use. For window users I have downloaded PyScripter in this video.",
                completed:false,
            },
            {
                lectureName:"Learn Javascript",
                iframeLink:'<iframe width="560" height="315" src="https://www.youtube.com/embed/JYnEbcTCyVI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                link:"https://youtu.be/20v8zSo2v18",
                instructor:"Sumit Malik",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
            {
                lectureName:"How to become fullstack developer",
                iframeLink:'<iframe width="560" height="315" src="https://www.youtube.com/embed/JYnEbcTCyVI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                link:"https://youtu.be/_k_c9nqzKN0",
                instructor:"Aditya Verma",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
            {
                lectureName:"How to programming",
                iframeLink:'<iframe width="560" height="315" src="https://www.youtube.com/embed/JYnEbcTCyVI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                link:"https://youtu.be/UmnCZ7-9yDY",
                instructor:"Aman Dhattarval",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
        ],

        designing:[
            {
                lectureName:"How to programming",
                iframeLink:'https://www.youtube.com/embed/JYnEbcTCyVI',
                link:"https://youtu.be/eKqY-oP1d_Y",
                instructor:"Shraddha Khapra",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
            {
                lectureName:"Python in 1 video",
                iframeLink:'https://www.youtube.com/embed/JYnEbcTCyVI',
                link:"https://youtu.be/vLqTf2b6GZw",
                instructor:"Aman Dhattarval and Shraddha Khapra",
                description:"This video shows installation of 2 Python editors, both are free to use. For window users I have downloaded PyScripter in this video.",
                completed:false,
            },
            {
                lectureName:"Learn Javascript",
                iframeLink:'<iframe width="560" height="315" src="https://www.youtube.com/embed/JYnEbcTCyVI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                link:"https://youtu.be/20v8zSo2v18",
                instructor:"Sumit Malik",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
            {
                lectureName:"How to become fullstack developer",
                iframeLink:'<iframe width="560" height="315" src="https://www.youtube.com/embed/JYnEbcTCyVI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                link:"https://youtu.be/_k_c9nqzKN0",
                instructor:"Aditya Verma",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
            {
                lectureName:"How to programming",
                iframeLink:'<iframe width="560" height="315" src="https://www.youtube.com/embed/JYnEbcTCyVI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                link:"https://youtu.be/UmnCZ7-9yDY",
                instructor:"Aman Dhattarval",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
        ],

        marketing:[
            {
                lectureName:"How to programming",
                iframeLink:'https://www.youtube.com/embed/JYnEbcTCyVI',
                link:"https://youtu.be/eKqY-oP1d_Y",
                instructor:"Shraddha Khapra",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
            {
                lectureName:"Python in 1 video",
                iframeLink:'https://www.youtube.com/embed/JYnEbcTCyVI',
                link:"https://youtu.be/vLqTf2b6GZw",
                instructor:"Aman Dhattarval and Shraddha Khapra",
                description:"This video shows installation of 2 Python editors, both are free to use. For window users I have downloaded PyScripter in this video.",
                completed:false,
            },
            {
                lectureName:"Learn Javascript",
                iframeLink:'<iframe width="560" height="315" src="https://www.youtube.com/embed/JYnEbcTCyVI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                link:"https://youtu.be/20v8zSo2v18",
                instructor:"Sumit Malik",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
            {
                lectureName:"How to become fullstack developer",
                iframeLink:'<iframe width="560" height="315" src="https://www.youtube.com/embed/JYnEbcTCyVI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                link:"https://youtu.be/_k_c9nqzKN0",
                instructor:"Aditya Verma",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
            {
                lectureName:"How to programming",
                iframeLink:'<iframe width="560" height="315" src="https://www.youtube.com/embed/JYnEbcTCyVI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                link:"https://youtu.be/UmnCZ7-9yDY",
                instructor:"Aman Dhattarval",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
        ],

        healthAndFitness:[
            {
                lectureName:"How to programming",
                iframeLink:'https://www.youtube.com/embed/JYnEbcTCyVI',
                link:"https://youtu.be/eKqY-oP1d_Y",
                instructor:"Shraddha Khapra",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
            {
                lectureName:"Python in 1 video",
                iframeLink:'https://www.youtube.com/embed/JYnEbcTCyVI',
                link:"https://youtu.be/vLqTf2b6GZw",
                instructor:"Aman Dhattarval and Shraddha Khapra",
                description:"This video shows installation of 2 Python editors, both are free to use. For window users I have downloaded PyScripter in this video.",
                completed:false,
            },
            {
                lectureName:"Learn Javascript",
                iframeLink:'<iframe width="560" height="315" src="https://www.youtube.com/embed/JYnEbcTCyVI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                link:"https://youtu.be/20v8zSo2v18",
                instructor:"Sumit Malik",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
            {
                lectureName:"How to become fullstack developer",
                iframeLink:'<iframe width="560" height="315" src="https://www.youtube.com/embed/JYnEbcTCyVI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                link:"https://youtu.be/_k_c9nqzKN0",
                instructor:"Aditya Verma",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
            {
                lectureName:"How to programming",
                iframeLink:'<iframe width="560" height="315" src="https://www.youtube.com/embed/JYnEbcTCyVI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                link:"https://youtu.be/UmnCZ7-9yDY",
                instructor:"Aman Dhattarval",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
        ],

        music:[
            {
                lectureName:"How to programming",
                iframeLink:'https://www.youtube.com/embed/JYnEbcTCyVI',
                link:"https://youtu.be/eKqY-oP1d_Y",
                instructor:"Shraddha Khapra",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
            {
                lectureName:"Python in 1 video",
                iframeLink:'https://www.youtube.com/embed/JYnEbcTCyVI',
                link:"https://youtu.be/vLqTf2b6GZw",
                instructor:"Aman Dhattarval and Shraddha Khapra",
                description:"This video shows installation of 2 Python editors, both are free to use. For window users I have downloaded PyScripter in this video.",
                completed:false,
            },
            {
                lectureName:"Learn Javascript",
                iframeLink:'<iframe width="560" height="315" src="https://www.youtube.com/embed/JYnEbcTCyVI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                link:"https://youtu.be/20v8zSo2v18",
                instructor:"Sumit Malik",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
            {
                lectureName:"How to become fullstack developer",
                iframeLink:'<iframe width="560" height="315" src="https://www.youtube.com/embed/JYnEbcTCyVI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                link:"https://youtu.be/_k_c9nqzKN0",
                instructor:"Aditya Verma",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
            {
                lectureName:"How to programming",
                iframeLink:'<iframe width="560" height="315" src="https://www.youtube.com/embed/JYnEbcTCyVI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                link:"https://youtu.be/UmnCZ7-9yDY",
                instructor:"Aman Dhattarval",
                description:"Are you worried about placements/internships? Want to prepare for companies like Microsoft, Amazon & Google? Join the course.",
                completed:false,
            },
        ],
    },

    jobs:[
        {
            // 1
            imgLink:"https://www.google.com/url?sa=i&url=https%3A%2F%2Fseosandwitch.com%2Famazon-offices-in-india%2F&psig=AOvVaw1ZfBqCTsAyMfWciH8UFDON&ust=1664126731024000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCLD80af5rfoCFQAAAAAdAAAAABAD",
            jobTitle:"Software Engineer",
            location:"Ahmedabad",
            salary:100000,
            skill:"Programming",
            jobType:"fulltime",
            companyName:"Amazon",
        },
        {
            // 2
            imgLink:"https://www.google.com/url?sa=i&url=https%3A%2F%2Fbetakit.com%2Fshopify-sheds-ottawa-office-space-amid-planned-toronto-expansion%2F&psig=AOvVaw1xjnnciGTxX169MRpmS1tp&ust=1664126756690000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCICL1bT5rfoCFQAAAAAdAAAAABAD",
            jobTitle:"UI / UX Designer",
            location:"Gandhinagar",
            salary:50000,
            skill:"Programming",
            jobType:"parttime",
            companyName:"Shopify",
        },
        {
            // 3
            imgLink:"https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.gensler.com%2Fprojects%2Fmathworks-lakeside-campus&psig=AOvVaw3646XNc2GiWQepYX5LKqHC&ust=1664126784675000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCOC948L5rfoCFQAAAAAdAAAAABAD",
            jobTitle:"User Experience Designer",
            location:"Surat",
            salary:50000,
            skill:"Programming",
            jobType:"fulltime",
            companyName:"Mathworks",
        },
        {
            // 4
            imgLink:"https://www.google.com/url?sa=i&url=https%3A%2F%2Fseosandwitch.com%2Famazon-offices-in-india%2F&psig=AOvVaw1ZfBqCTsAyMfWciH8UFDON&ust=1664126731024000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCLD80af5rfoCFQAAAAAdAAAAABAD",
            jobTitle:"Product Designer",
            location:"Ahmedabad",
            salary:100000,
            skill:"Programming",
            jobType:"fulltime",
            companyName:"Amazon",
        },
        {
            // 5
            imgLink:"https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.99acres.com%2Fvitthal-velocity-nava-naroda-ahmedabad-east-npxid-r63783&psig=AOvVaw1ayXeCoaxT7WD8i9Kv4IFy&ust=1664126831788000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCKCA8dn5rfoCFQAAAAAdAAAAABAf",
            jobTitle:"House Keeping",
            location:"Ahmedabad",
            salary:5000,
            skill:"House Keeping",
            jobType:"parttime",
            companyName:"Vithhal Velocity",
        },
        {
            // 6
            imgLink:"https://play.google.com/store/apps/details?id=com.vidyalaya.shreepanchtirthvidyalayapp&hl=en_SG&gl=US",
            jobTitle:"Maths Teacher",
            location:"Ahmedabad",
            salary:56000,
            skill:"Teaching",
            jobType:"fulltime",
            companyName:"Shree Panchatirth Vidhyalaya",
        },
        {
            // 7
            imgLink:"https://www.google.com/url?sa=i&url=https%3A%2F%2Fabout.google%2Flocations%2F&psig=AOvVaw3XVkgT0EVDRBqBWV8DJ5p8&ust=1664126976175000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCKiQgJ36rfoCFQAAAAAdAAAAABAN",
            jobTitle:"Software Development Engineer",
            location:"Vadodara",
            salary:100000,
            skill:"Programming",
            jobType:"fulltime",
            companyName:"Google",
        },
        {
            // 8
            imgLink:"https://www.google.com/url?sa=i&url=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Ftech-office&psig=AOvVaw02D9TIxixnwPanB0YMgv38&ust=1664127008595000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCPiAhK36rfoCFQAAAAAdAAAAABAD",
            jobTitle:"SEO",
            location:"Surat",
            salary:10000,
            skill:"Programming",
            jobType:"fulltime",
            companyName:"Desi Tech",
        },
        {
            // 9
            imgLink:"https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.npr.org%2F2020%2F04%2F24%2F840397136%2Fthe-office-as-we-knew-it-isnt-coming-back-anytime-soon-maybe-it-s-changed-foreve&psig=AOvVaw3XHmtrPAmwbhG3AllDWbrD&ust=1664127058945000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCPinrMX6rfoCFQAAAAAdAAAAABAD",
            jobTitle:"Full stack developer",
            location:"Ahmedabad",
            salary:500000,
            skill:"Programming",
            jobType:"fulltime",
            companyName:"Rathod PVT. LTD.",
        },
        {
            // 10
            imgLink:"https://www.google.com/url?sa=i&url=http%3A%2F%2Fdipsnikol.org%2Factivities%2Fswach-bharat-abhyan%2F&psig=AOvVaw1VRsQ92ICx3Lw1YiN3eq6S&ust=1664127118058000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCICf6OD6rfoCFQAAAAAdAAAAABAN",
            jobTitle:"Physics Teacher",
            location:"Vadodara",
            salary:35000,
            skill:"Teaching",
            jobType:"fulltime",
            companyName:"Devashya School",
        },
        {
            // 11
            imgLink:"https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.tripadvisor.in%2FRestaurant_Review-g297608-d1203672-Reviews-Patang-Ahmedabad_Ahmedabad_District_Gujarat.html&psig=AOvVaw2w5EgPlppRxgPuYpdMVJaO&ust=1664127180576000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCLjHsv76rfoCFQAAAAAdAAAAABAR",
            jobTitle:"Cheff",
            location:"Surat",
            salary: 7000,
            skill:"Cooking",
            jobType:"parttime",
            companyName:"Patang Hotel",
        },
        {
            // 12
            imgLink:"https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.gqindia.com%2Flive-well%2Fcontent%2F5-places-where-you-can-have-the-best-vada-pav-in-mumbai&psig=AOvVaw3Dy5GBZ8AgFTviBTZEQgue&ust=1664127213777000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCPj4sI77rfoCFQAAAAAdAAAAABAD",
            jobTitle:"Cheff",
            location:"Ganshinagar",
            salary: 4500,
            skill:"Cooking",
            jobType:"parttime",
            companyName:"Lakshay Vadapav",
        },
        {
            // 13
            imgLink:"https://www.google.com/url?sa=i&url=https%3A%2F%2Fcookingfromheart.com%2Fkutchi-dabeli-kachchi-dabeli%2F&psig=AOvVaw2wetg1TZG8eQZoFVX1GWiK&ust=1664127231708000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCMji-Jb7rfoCFQAAAAAdAAAAABAH",
            jobTitle:"Cheff",
            location:"Vadodara",
            salary: 5000,
            skill:"Programming",
            jobType:"fulltime",
            companyName:"Jay Dabeli",
        },
        {
            // 14
            imgLink:"https://www.google.com/url?sa=i&url=https%3A%2F%2Fcookpad.com%2Fus%2Frecipes%2F11437233-veg-manchurian&psig=AOvVaw2FYU4hWLpL3GTRrL7-4fm4&ust=1664127281547000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCND9t637rfoCFQAAAAAdAAAAABA6",
            jobTitle:"Cheff",
            location:"Ahmedabad",
            salary: 10000,
            skill:"Programming",
            jobType:"fulltime",
            companyName:"Umang Manchurian",
        },
        {
            // 15
            imgLink:"https://www.google.com/url?sa=i&url=https%3A%2F%2Feconomictimes.indiatimes.com%2Fmagazines%2Fpanache%2Freliance-digital-sale-oppo-r17-at-rs-19999-55-inch-tvs-starting-at-rs-39900%2Farticleshow%2F70607067.cms&psig=AOvVaw2c9QScV5Oyb1Y7XC-ABuCz&ust=1664127343663000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCMCPss77rfoCFQAAAAAdAAAAABAD",
            jobTitle:"Software Engineer",
            location:"Ahmedabad",
            salary: 80000,
            skill:"Programming",
            jobType:"fulltime",
            companyName:"Reliance Digital",
        },
        {
            // 16
            imgLink:"https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.businesstoday.in%2Flatest%2Fcorporate%2Fstory%2Ftcs-takes-the-social-media-way-to-bring-employees-back-to-office-but-employees-are-not-convinced-347622-2022-09-19&psig=AOvVaw2_dx9nuFmj5yXRYB9VqSMw&ust=1664127368655000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCPD-wNf7rfoCFQAAAAAdAAAAABAH",
            jobTitle:"Software Engineer",
            location:"Ahmedabad",
            salary: 75000,
            skill:"Programming",
            jobType:"fulltime",
            companyName:"TCS",
        },
    ],
}
